# Continuous integration with travis
language: r
sudo: required

r_binary_packages:
 - rgdal
 - rgeos
 - raster
 - mgcv
 - snowfall
 - deldir
 - sp
 
 # Warnings don't fail build
warnings_are_errors: false

## Email notification if the package pass status changes
notifications:
email:
  on_success: change
  on_failure: change  

after_success:
 - Rscript -e 'library(covr);codecov()'

matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
    - r: devel
      r_github_packages: andrewzm/INLA
    - r: devel
      env: _R_CHECK_FORCE_SUGGESTS_=false
      install: R -e 'install.packages("devtools", dep = TRUE);devtools::install_deps(dep = c("Depends", "Imports"))'


